quarkus.http.port=8081

# Configurações do Banco de Dados H2
quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=sa
quarkus.datasource.jdbc.url=jdbc:h2:mem:unifor_db;DB_CLOSE_DELAY=-1

# Padrão correto para o Hibernate gerar as tabelas automaticamente nas versões novas
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# Interface Web do H2 (Ajustado para o formato correto que o Quarkus espera)
quarkus.h2.console.settings.web-allow-others=true