quarkus.http.port=8081
%test.quarkus.http.port=8083

quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=sa
quarkus.datasource.jdbc.url=jdbc:h2:mem:unifor_db;DB_CLOSE_DELAY=-1
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql

quarkus.http.root-path=/api

quarkus.h2.console.settings.web-allow-others=true

smallrye.jwt.sign.key.string=uma-chave-secreta-muito-longa-e-segura-para-o-desafio-unifor-2026
mp.jwt.verify.publickey.algorithm=HS256
mp.jwt.verify.publickey=uma-chave-secreta-muito-longa-e-segura-para-o-desafio-unifor-2026
mp.jwt.verify.issuer=unifor-auth-api

quarkus.swagger-ui.always-include=true

quarkus.swagger-ui.path=/swagger