quarkus.http.port=8081
%test.quarkus.http.port=8083

quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=sa
quarkus.datasource.jdbc.url=jdbc:h2:mem:unifor_db;DB_CLOSE_DELAY=-1
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql

# ? Ativado: Aplica /api no início de todos os controllers do projeto
quarkus.http.root-path=/api

quarkus.h2.console.settings.web-allow-others=true

# ? Comentado: Deixamos o CorsConfig.kt cuidar disso programaticamente
# quarkus.http.cors=true
# quarkus.http.cors.origins=http://localhost:4200
# quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
# quarkus.http.cors.headers=*
# quarkus.http.auth.permission.cors.paths=/*
# quarkus.http.auth.permission.cors.methods=OPTIONS
# quarkus.http.auth.permission.cors.policy=permit

smallrye.jwt.sign.key.string=uma-chave-secreta-muito-longa-e-segura-para-o-desafio-unifor-2026
mp.jwt.verify.publickey.algorithm=HS256
mp.jwt.verify.publickey=uma-chave-secreta-muito-longa-e-segura-para-o-desafio-unifor-2026
mp.jwt.verify.issuer=unifor-auth-api